- hosts: splunk_all
  become: yes
  roles:
  - splunk_all
  tasks:
  - name: pause the script for 60 seconds
    pause:
      seconds: 60

- hosts: dslm
  become: yes
  roles:
  - dslm_cm
  tasks:
  - name: pause the script for 60 seconds
    pause:
      seconds: 60

- hosts: indexers
  become: yes
  roles:
  - indexer
  tasks:
  - name: pause the script for 60 seconds
    pause:
      seconds: 60

- hosts: sh1
  become: yes
  roles:
  - search_head1

- hosts: sh2
  become: yes
  roles:
  - search_head2

- hosts: sh1
  become: yes
  roles:
  - search_head3
