---
- name: create a user file
  file:
    path: /opt/splunk/etc/system/local/user-seed.conf
    state: touch
    owner: splunk
    group: splunk
    mode: 0660
- name: add multiple lines in a file
  lineinfile:
    dest: /opt/splunk/etc/system/local/user-seed.conf
    line: "{{ item }}"
  with_items:
    - "[user_info]"
    - "USERNAME = admin"
    - "PASSWORD = Welcome123$"
- name: restart splunk
  service: 
    name: splunk 
    state: restarted
