---
- name: Install splunk
  yum:
    name: /tmp/splunk-7.1.0-2e75b3406c5b-linux-2.6-x86_64.rpm
  
- name: accept license
  shell: /opt/splunk/bin/splunk start --answer-yes --no-prompt --accept-license
  become: yes
  become_user: splunk
- name: enable init script
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk
  become: yes
  #become_user: splunk
