---
- name: add multiple lines in a file
  lineinfile:
    dest: /opt/splunk/etc/system/local/server.conf
    line: "{{ item }}"
  with_items:
    - "[clustering]"
    - "cluster_label = SingleSite Cluster"
    - "mode = master"
    - "replication_factor = 2"
